// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<AnnounceDataForDisplay>))]
public class AnnounceDataForDisplay
{
    [Key("id")] public int id; // 0x10
}
