// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CharacterStoryReadResponse>))]
public class CharacterStoryReadResponse : ResponseCommon
{
    [Key("data")] public CharacterStoryReadResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<CharacterStoryReadResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("character_story_data")] public CharacterStoryData character_story_data; // 0x10
    }
}
