// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CharacterStoryReadRequest>))]
public class CharacterStoryReadRequest : RequestBase<CharacterStoryReadResponse>
{
    [Key("episode_id")] public int episode_id; // 0x88
}
