// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CollectRaidSaveCharaDressInfoRequest>))]
public class CollectRaidSaveCharaDressInfoRequest : RequestBase<CollectRaidSaveCharaDressInfoResponse>
{
    [Key("episode_id")] public int episode_id; // 0x88
    [Key("user_chara_dress_info")] public CollectRaidUserCharaDressInfo user_chara_dress_info; // 0x90
}
