// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CollectRaidSaveCharaDressInfoResponse>))]
public class CollectRaidSaveCharaDressInfoResponse : ResponseCommon
{
    [Key("data")] public CollectRaidSaveCharaDressInfoResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<CollectRaidSaveCharaDressInfoResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
