// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<CollectRaidUserCharaDressInfo>))]
public class CollectRaidUserCharaDressInfo
{
    [Key("chara_id")] public int chara_id; // 0x10
    [Key("dress_id")] public int dress_id; // 0x14
}
