// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugRaceFixStartDelayTime>))]
public class DebugRaceFixStartDelayTime
{
    [Key("frame_order")] public int frame_order; // 0x10
    [Key("start_delay_time")] public float start_delay_time; // 0x14
}
