// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugRaceFixFinishOrder>))]
public class DebugRaceFixFinishOrder
{
    [Key("frame_order")] public int frame_order; // 0x10
    [Key("finish_order")] public int finish_order; // 0x14
}
