// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugRaceFixBashinDiffBehind>))]
public class DebugRaceFixBashinDiffBehind
{
    [Key("frame_order")] public int frame_order; // 0x10
    [Key("bashin_diff_behind")] public float bashin_diff_behind; // 0x14
}
