// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugRaceFixBashinDiffFromTop>))]
public class DebugRaceFixBashinDiffFromTop
{
    [Key("frame_order")] public int frame_order; // 0x10
    [Key("bashin_diff_from_top")] public float bashin_diff_from_top; // 0x14
}
