// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<DebugRaceSimulateAPIParam>))]
public class DebugRaceSimulateAPIParam
{
    [Key("debug_result_rank")] public DebugRaceFixFinishOrder[] debug_result_rank; // 0x10
    [Key("fix_bashin_diff_behind_array")] public DebugRaceFixBashinDiffBehind[] fix_bashin_diff_behind_array; // 0x18
    [Key("fix_bashin_diff_from_top_array")] public DebugRaceFixBashinDiffFromTop[] fix_bashin_diff_from_top_array; // 0x20
    [Key("fix_start_delay_time_array")] public DebugRaceFixStartDelayTime[] fix_start_delay_time_array; // 0x28
    [Key("is_record_interval_simulate")] public int is_record_interval_simulate; // 0x30
}
