// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ExtraFactorInfo>))]
public class ExtraFactorInfo
{
    [Key("factor_id")] public int factor_id; // 0x10
    [Key("level")] public int level; // 0x14
    [Key("effected_trainer_skill_id_array")] public int[] effected_trainer_skill_id_array; // 0x18
    [Key("before_factor_id")] public int before_factor_id; // 0x20
}
