// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ExtraSkillTips>))]
public class ExtraSkillTips
{
    [Key("group_id")] public int group_id; // 0x10
    [Key("rarity")] public int rarity; // 0x14
    [Key("level")] public int level; // 0x18
    [Key("effected_trainer_skill_id_array")] public int[] effected_trainer_skill_id_array; // 0x20
}
