// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FactorResearchTaskPredictResponse>))]
public class FactorResearchTaskPredictResponse : ResponseCommon
{
    [Key("data")] public FactorResearchTaskPredictResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<FactorResearchTaskPredictResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("clear_factor_research_task_list_id_array")] public int[] clear_factor_research_task_list_id_array; // 0x10
        [Key("add_reward_point")] public int add_reward_point; // 0x18
        [Key("add_reward_item_array")] public ResponseItem[] add_reward_item_array; // 0x20
    }
}
