// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FactorResearchTaskPresentationResponse>))]
public class FactorResearchTaskPresentationResponse : ResponseCommon
{
    [Key("data")] public FactorResearchTaskPresentationResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<FactorResearchTaskPresentationResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("add_reward_point")] public int add_reward_point; // 0x10
        [Key("add_reward_item_array")] public ResponseItem[] add_reward_item_array; // 0x18
        [Key("reward_summary_info")] public RewardSummaryInfo reward_summary_info; // 0x20
        [Key("factor_research_task_info")] public FactorResearchTaskInfo factor_research_task_info; // 0x28
        [Key("factor_research_all_completed_reward_flag")] public int factor_research_all_completed_reward_flag; // 0x30
        [Key("factor_update_item_array")] public ResponseItem[] factor_update_item_array; // 0x38
    }
}
