// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FactorResearchTaskInfo>))]
public class FactorResearchTaskInfo
{
    [Key("total_reward_point")] public int total_reward_point; // 0x10
    [Key("cleared_factor_research_task_list_id_array")] public int[] cleared_factor_research_task_list_id_array; // 0x18
    [Key("presented_trained_chara_id_array")] public int[] presented_trained_chara_id_array; // 0x20
}
