// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FactorResearchWhiteFactorUpdateResponse>))]
public class FactorResearchWhiteFactorUpdateResponse : ResponseCommon
{
    [Key("data")] public FactorResearchWhiteFactorUpdateResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<FactorResearchWhiteFactorUpdateResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("trained_chara")] public TrainedChara trained_chara; // 0x10
        [Key("factor_update_item")] public ResponseItem factor_update_item; // 0x18
    }
}
