// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FactorResearchWhiteFactorUpdateRequest>))]
public class FactorResearchWhiteFactorUpdateRequest : RequestBase<FactorResearchWhiteFactorUpdateResponse>
{
    [Key("trained_chara_id")] public int trained_chara_id; // 0x88
    [Key("factor_id")] public int factor_id; // 0x8C
}
