// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FetchRaceFitAssistanceRequest>))]
public class FetchRaceFitAssistanceRequest : RequestBase<FetchRaceFitAssistanceResponse>
{
    [Key("disable_time_recording_flag")] public bool disable_time_recording_flag; // 0x88
}
