// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FriendSearchSupportCardResponse>))]
public class FriendSearchSupportCardResponse : ResponseCommon
{
    [Key("data")] public FriendSearchSupportCardResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<FriendSearchSupportCardResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("summary_user_info_array")] public UserInfoAtFriend[] summary_user_info_array; // 0x10
        [Key("support_card_data_array")] public UserSupportCard[] support_card_data_array; // 0x18
    }
}
