// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FriendSearchSupportCardRequest>))]
public class FriendSearchSupportCardRequest : RequestBase<FriendSearchSupportCardResponse>
{
    [Key("support_card_id")] public int support_card_id; // 0x88
    [Key("exclude_viewer_id_array")] public long[] exclude_viewer_id_array; // 0x90
}
