// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FriendSearchTrainedCharaRequest>))]
public class FriendSearchTrainedCharaRequest : RequestBase<FriendSearchTrainedCharaResponse>
{
    [Key("card_id_array")] public int[] card_id_array; // 0x88
    [Key("factor_group_id_status_array")] public int[] factor_group_id_status_array; // 0x90
    [Key("factor_group_id_proper_array")] public int[] factor_group_id_proper_array; // 0x98
    [Key("factor_rarity_min_status")] public int factor_rarity_min_status; // 0xA0
    [Key("factor_rarity_min_proper")] public int factor_rarity_min_proper; // 0xA4
}
