// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<FriendSearchTrainedCharaResponse>))]
public class FriendSearchTrainedCharaResponse : ResponseCommon
{
    [Key("data")] public FriendSearchTrainedCharaResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<FriendSearchTrainedCharaResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("user_list")] public UserFriend[] user_list; // 0x10
        [Key("succession_info_array")] public FriendSuccessionInfo[] succession_info_array; // 0x18
        [Key("user_info_summary_list")] public UserInfoAtFriend[] user_info_summary_list; // 0x20
    }
}
