// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<GenerateSuccessionTempChara>))]
public class GenerateSuccessionTempChara
{
    [Key("position")] public int position; // 0x10
    [Key("generate_succession_chara")] public TrainedChara generate_succession_chara; // 0x18
    [Key("factor_info_array")] public ExtraFactorInfo[] factor_info_array; // 0x20
}
