// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<HomeCharacterDressInfo>))]
public class HomeCharacterDressInfo
{
    [Key("position1_chara_id")] public int position1_chara_id; // 0x10
    [Key("position2_chara_id")] public int position2_chara_id; // 0x14
    [Key("position3_chara_id")] public int position3_chara_id; // 0x18
    [Key("position4_chara_id")] public int position4_chara_id; // 0x1C
    [Key("position1_cloth_id")] public int position1_cloth_id; // 0x20
    [Key("position2_cloth_id")] public int position2_cloth_id; // 0x24
    [Key("position3_cloth_id")] public int position3_cloth_id; // 0x28
    [Key("position4_cloth_id")] public int position4_cloth_id; // 0x2C
    [Key("position1_cloth_color_id")] public int position1_cloth_color_id; // 0x30
    [Key("position2_cloth_color_id")] public int position2_cloth_color_id; // 0x34
    [Key("position3_cloth_color_id")] public int position3_cloth_color_id; // 0x38
    [Key("position4_cloth_color_id")] public int position4_cloth_color_id; // 0x3C
}
