// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<IdleSingleModeContinueSetting>))]
public class IdleSingleModeContinueSetting
{
    [Key("continue_flag")] public bool continue_flag; // 0x10
    [Key("not_continue_flag_unsuitable_race")] public bool not_continue_flag_unsuitable_race; // 0x11
    [Key("not_continue_flag_below_g2")] public bool not_continue_flag_below_g2; // 0x12
}
