// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<IdleSingleModeContinueInfo>))]
public class IdleSingleModeContinueInfo
{
    [Key("continue_item_before_num")] public long continue_item_before_num; // 0x10
    [Key("continue_item_after_num")] public long continue_item_after_num; // 0x18
}
