// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<IdleSingleModeGainSkillLog>))]
public class IdleSingleModeGainSkillLog
{
    [Key("skill_id")] public int skill_id; // 0x10
    [Key("gain_index")] public int gain_index; // 0x14
}
