// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<IdleSingleModeProgressInfo>))]
public class IdleSingleModeProgressInfo
{
    [Key("chara_info")] public SingleModeChara chara_info; // 0x10
    [Key("start_time")] public string start_time; // 0x18
    [Key("end_time")] public string end_time; // 0x20
    [Key("dress_id")] public int dress_id; // 0x28
    [Key("story_event_mission_list")] public UserMission[] story_event_mission_list; // 0x30
    [Key("story_event_chara_bonus_list")] public StoryEventCharaBonus[] story_event_chara_bonus_list; // 0x38
    [Key("effected_trainer_skill_id_array")] public int[] effected_trainer_skill_id_array; // 0x40
}
