// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<IdleSingleModeSkillTipsLog>))]
public class IdleSingleModeSkillTipsLog
{
    [Key("gain_index")] public int gain_index; // 0x10
    [Key("skill_tips")] public SkillTips skill_tips; // 0x18
}
