// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<PosterUrlResponse>))]
public class PosterUrlResponse : ResponseCommon
{
    [Key("data")] public PosterUrlResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<PosterUrlResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("url")] public string url; // 0x10
    }
}
