// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<PosterUrlRequest>))]
public class PosterUrlRequest : RequestBase<PosterUrlResponse>
{
    [Key("poster_id")] public int poster_id; // 0x88
}
