// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ReadInfoAnnounceRequest>))]
public class ReadInfoAnnounceRequest : RequestBase<ReadInfoAnnounceResponse>
{
    [Key("add_announce_data_array")] public AnnounceDataForRegist[] add_announce_data_array; // 0x88
}
