// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ReadInfoUmaplanBonusReceivedDialogResponse>))]
public class ReadInfoUmaplanBonusReceivedDialogResponse : ResponseCommon
{
    [Key("data")] public ReadInfoUmaplanBonusReceivedDialogResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<ReadInfoUmaplanBonusReceivedDialogResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
