// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<ReadInfoAnnounceResponse>))]
public class ReadInfoAnnounceResponse : ResponseCommon
{
    [Key("data")] public ReadInfoAnnounceResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<ReadInfoAnnounceResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("announce_data_array")] public AnnounceDataForDisplay[] announce_data_array; // 0x10
    }
}
