// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetExtensionSharePeriodRequest>))]
public class SkillSetExtensionSharePeriodRequest : RequestBase<SkillSetExtensionSharePeriodResponse>
{
    [Key("share_id")] public long share_id; // 0x88
    [Key("expiration_time")] public string expiration_time; // 0x90
}
