// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetDeck>))]
public class SkillSetDeck
{
    [Key("skill_set_deck_id")] public int skill_set_deck_id; // 0x10
    [Key("deck_name")] public string deck_name; // 0x18
    [Key("share_id")] public long share_id; // 0x20
    [Key("expiration_time")] public string expiration_time; // 0x28
    [Key("skill_set_skill_array")] public SkillSetSkill[] skill_set_skill_array; // 0x30
}
