// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetChangeDeckSkillResponse>))]
public class SkillSetChangeDeckSkillResponse : ResponseCommon
{
    [Key("data")] public SkillSetChangeDeckSkillResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetChangeDeckSkillResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("skill_set_deck")] public SkillSetDeck skill_set_deck; // 0x10
    }
}
