// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetPolicyGetSkill>))]
public class SkillSetPolicyGetSkill
{
    [Key("skill_point_allocate_priority_type")] public int skill_point_allocate_priority_type; // 0x10
    [Key("super_priority_allocate_priority_type")] public int super_priority_allocate_priority_type; // 0x14
    [Key("super_priority_min_hint_lv_required_to_skill_get")] public int super_priority_min_hint_lv_required_to_skill_get; // 0x18
    [Key("high_priority_allocate_priority_type")] public int high_priority_allocate_priority_type; // 0x1C
    [Key("high_priority_min_hint_lv_required_to_skill_get")] public int high_priority_min_hint_lv_required_to_skill_get; // 0x20
    [Key("normal_priority_allocate_priority_type")] public int normal_priority_allocate_priority_type; // 0x24
    [Key("normal_priority_min_hint_lv_required_to_skill_get")] public int normal_priority_min_hint_lv_required_to_skill_get; // 0x28
    [Key("excess_point_allocate_setting_flag_not_include_skill_set")] public bool excess_point_allocate_setting_flag_not_include_skill_set; // 0x2C
}
