// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetExtensionSharePeriodResponse>))]
public class SkillSetExtensionSharePeriodResponse : ResponseCommon
{
    [Key("data")] public SkillSetExtensionSharePeriodResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetExtensionSharePeriodResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("num_of_share_on_the_day")] public int num_of_share_on_the_day; // 0x10
    }
}
