// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetChangePolicyGetSkillResponse>))]
public class SkillSetChangePolicyGetSkillResponse : ResponseCommon
{
    [Key("data")] public SkillSetChangePolicyGetSkillResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetChangePolicyGetSkillResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
