// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetShareResponse>))]
public class SkillSetShareResponse : ResponseCommon
{
    [Key("data")] public SkillSetShareResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetShareResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("share_id")] public long share_id; // 0x10
        [Key("expiration_time")] public string expiration_time; // 0x18
        [Key("num_of_share_on_the_day")] public int num_of_share_on_the_day; // 0x20
    }
}
