// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetGetExtensionPeriodResponse>))]
public class SkillSetGetExtensionPeriodResponse : ResponseCommon
{
    [Key("data")] public SkillSetGetExtensionPeriodResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetGetExtensionPeriodResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("expiration_time")] public string expiration_time; // 0x10
    }
}
