// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetIndexResponse>))]
public class SkillSetIndexResponse : ResponseCommon
{
    [Key("data")] public SkillSetIndexResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetIndexResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("skill_set_info")] public SkillSetInfo skill_set_info; // 0x10
        [Key("training_roadmap_selected_info")] public TrainingRoadmapSelectedInfo training_roadmap_selected_info; // 0x18
    }
}
