// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetGetShareInfoRequest>))]
public class SkillSetGetShareInfoRequest : RequestBase<SkillSetGetShareInfoResponse>
{
    [Key("share_id")] public long share_id; // 0x88
}
