// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetInfo>))]
public class SkillSetInfo
{
    [Key("skill_set_deck_array")] public SkillSetDeck[] skill_set_deck_array; // 0x10
    [Key("skill_set_policy_get_skill")] public SkillSetPolicyGetSkill skill_set_policy_get_skill; // 0x18
    [Key("auto_call_skill_set_deck_id")] public int auto_call_skill_set_deck_id; // 0x20
    [Key("num_of_share_on_the_day")] public int num_of_share_on_the_day; // 0x24
}
