// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetGetShareInfoResponse>))]
public class SkillSetGetShareInfoResponse : ResponseCommon
{
    [Key("data")] public SkillSetGetShareInfoResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetGetShareInfoResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("deck_name")] public string deck_name; // 0x10
        [Key("skill_set_skill_array")] public SkillSetSkill[] skill_set_skill_array; // 0x18
    }
}
