// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetSkill>))]
public class SkillSetSkill
{
    [Key("priority_type")] public int priority_type; // 0x10
    [Key("skill_id")] public int skill_id; // 0x14
    [Key("priority_value")] public int priority_value; // 0x18
}
