// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetChangeAutoCallDeckIdResponse>))]
public class SkillSetChangeAutoCallDeckIdResponse : ResponseCommon
{
    [Key("data")] public SkillSetChangeAutoCallDeckIdResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetChangeAutoCallDeckIdResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
