// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetChangeDeckSkillAndNameRequest>))]
public class SkillSetChangeDeckSkillAndNameRequest : RequestBase<SkillSetChangeDeckSkillAndNameResponse>
{
    [Key("skill_set_deck_id")] public int skill_set_deck_id; // 0x88
    [Key("skill_set_skill_array")] public SkillSetSkill[] skill_set_skill_array; // 0x90
    [Key("change_type")] public int change_type; // 0x98
    [Key("deck_name")] public string deck_name; // 0xA0
}
