// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetChangeDeckNameResponse>))]
public class SkillSetChangeDeckNameResponse : ResponseCommon
{
    [Key("data")] public SkillSetChangeDeckNameResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetChangeDeckNameResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("skill_set_deck")] public SkillSetDeck skill_set_deck; // 0x10
    }
}
