// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetChangeDeckNameRequest>))]
public class SkillSetChangeDeckNameRequest : RequestBase<SkillSetChangeDeckNameResponse>
{
    [Key("skill_set_deck_id")] public int skill_set_deck_id; // 0x88
    [Key("deck_name")] public string deck_name; // 0x90
}
