// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetChangePolicyGetSkillRequest>))]
public class SkillSetChangePolicyGetSkillRequest : RequestBase<SkillSetChangePolicyGetSkillResponse>
{
    [Key("skill_set_policy_get_skill")] public SkillSetPolicyGetSkill skill_set_policy_get_skill; // 0x88
}
