// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetShareRequest>))]
public class SkillSetShareRequest : RequestBase<SkillSetShareResponse>
{
    [Key("skill_set_deck_id")] public int skill_set_deck_id; // 0x88
}
