// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SkillSetChangeDeckSkillRequest>))]
public class SkillSetChangeDeckSkillRequest : RequestBase<SkillSetChangeDeckSkillResponse>
{
    [Key("skill_set_deck_id")] public int skill_set_deck_id; // 0x88
    [Key("skill_set_skill_array")] public SkillSetSkill[] skill_set_skill_array; // 0x90
    [Key("change_type")] public int change_type; // 0x98
}
