// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SupportCardGetExtendMasterInfoResponse>))]
public class SupportCardGetExtendMasterInfoResponse : ResponseCommon
{
    [Key("data")] public SupportCardGetExtendMasterInfoResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<SupportCardGetExtendMasterInfoResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("event_skill_info_array")] public SupportCardEventSkillInfo[] event_skill_info_array; // 0x10
        [Key("skill_filter_info_array")] public SupportCardSkillFilterInfo[] skill_filter_info_array; // 0x18
    }
}
