// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SupportCardSkillFilterInfo>))]
public class SupportCardSkillFilterInfo
{
    [Key("skill_id")] public int skill_id; // 0x10
    [Key("start_time")] public long start_time; // 0x18
}
