// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<SupportCardEventSkillInfo>))]
public class SupportCardEventSkillInfo
{
    [Key("support_card_id")] public int support_card_id; // 0x10
    [Key("event_skill_id_array")] public int[] event_skill_id_array; // 0x18
}
