// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainerSkillSaveShowRefundDialogResponse>))]
public class TrainerSkillSaveShowRefundDialogResponse : ResponseCommon
{
    [Key("data")] public TrainerSkillSaveShowRefundDialogResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainerSkillSaveShowRefundDialogResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
