// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingReportIndexResponse>))]
public class TrainingReportIndexResponse : ResponseCommon
{
    [Key("data")] public TrainingReportIndexResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingReportIndexResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("training_report_info")] public TrainingReportInfo training_report_info; // 0x10
        [Key("reward_info_array")] public DisplayRewardInfo[] reward_info_array; // 0x18
        [Key("reward_summary_info")] public RewardSummaryInfo reward_summary_info; // 0x20
        [Key("season_change_flag")] public bool season_change_flag; // 0x28
        [Key("premium_pass_reward_confirm_dialog_flag")] public bool premium_pass_reward_confirm_dialog_flag; // 0x29
    }
}
