// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapCompareSource>))]
public class TrainingRoadmapCompareSource
{
    [Key("identifier")] public TrainingRoadmapCharacterIdentifier identifier; // 0x10
    [Key("compare_trained_chara_id")] public int compare_trained_chara_id; // 0x18
    [Key("compare_chara_owner_viewer_id")] public long compare_chara_owner_viewer_id; // 0x20
    [Key("compare_type")] public int compare_type; // 0x28
}
