// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapUpdatePlanResponse>))]
public class TrainingRoadmapUpdatePlanResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapUpdatePlanResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapUpdatePlanResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("plan")] public TrainingRoadmapPlan plan; // 0x10
    }
}
