// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapPreImportShareResponse>))]
public class TrainingRoadmapPreImportShareResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapPreImportShareResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapPreImportShareResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("type")] public int type; // 0x10
        [Key("title")] public string title; // 0x18
        [Key("character")] public TrainingRoadmapChara character; // 0x20
        [Key("succession_character_array")] public TrainingRoadmapSuccessionChara[] succession_character_array; // 0x28
    }
}
