// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainerSkillActivateResponse>))]
public class TrainerSkillActivateResponse : ResponseCommon
{
    [Key("data")] public TrainerSkillActivateResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainerSkillActivateResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("trainer_skill_array")] public TrainerSkillTrainerSkill[] trainer_skill_array; // 0x10
        [Key("user_item_array")] public UserItem[] user_item_array; // 0x18
        [Key("maintenance_id_array")] public int[] maintenance_id_array; // 0x20
    }
}
