// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapUpdateSuccessionCharacterResponse>))]
public class TrainingRoadmapUpdateSuccessionCharacterResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapUpdateSuccessionCharacterResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapUpdateSuccessionCharacterResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("succession_character")] public TrainingRoadmapSuccessionChara succession_character; // 0x10
    }
}
