// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapSuccessionChara>))]
public class TrainingRoadmapSuccessionChara
{
    [Key("identifier")] public TrainingRoadmapCharacterIdentifier identifier; // 0x10
    [Key("card_id")] public int card_id; // 0x18
    [Key("param_factor_id")] public int param_factor_id; // 0x1C
    [Key("proper_factor_id")] public int proper_factor_id; // 0x20
    [Key("chara_factor_id")] public int chara_factor_id; // 0x24
    [Key("top_factor_id_array")] public int[] top_factor_id_array; // 0x28
    [Key("high_factor_id_array")] public int[] high_factor_id_array; // 0x30
    [Key("low_factor_id_array")] public int[] low_factor_id_array; // 0x38
    [Key("single_mode_program_id_array")] public int[] single_mode_program_id_array; // 0x40
    [Key("reserved_race_array")] public SingleModeReservedRace[] reserved_race_array; // 0x48
    [Key("support_card_id_array")] public int[] support_card_id_array; // 0x50
}
