// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapSuccessionPlan>))]
public class TrainingRoadmapSuccessionPlan
{
    [Key("plan_id")] public int plan_id; // 0x10
    [Key("title")] public string title; // 0x18
}
