// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapSameContentShareInfo>))]
public class TrainingRoadmapSameContentShareInfo
{
    [Key("identifier")] public TrainingRoadmapCharacterIdentifier identifier; // 0x10
    [Key("share_id")] public long share_id; // 0x18
}
