// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainerSkillSaveNotifyLastCheckTimeResponse>))]
public class TrainerSkillSaveNotifyLastCheckTimeResponse : ResponseCommon
{
    [Key("data")] public TrainerSkillSaveNotifyLastCheckTimeResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainerSkillSaveNotifyLastCheckTimeResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
