// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapAddCharacterResponse>))]
public class TrainingRoadmapAddCharacterResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapAddCharacterResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapAddCharacterResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("character_array")] public TrainingRoadmapChara[] character_array; // 0x10
    }
}
