// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapLoadResponse>))]
public class TrainingRoadmapLoadResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapLoadResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapLoadResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("plan_array")] public TrainingRoadmapPlan[] plan_array; // 0x10
        [Key("character_array")] public TrainingRoadmapChara[] character_array; // 0x18
        [Key("succession_plan_array")] public TrainingRoadmapSuccessionPlan[] succession_plan_array; // 0x20
        [Key("succession_character_array")] public TrainingRoadmapSuccessionChara[] succession_character_array; // 0x28
        [Key("selected_character_identifier")] public TrainingRoadmapCharacterIdentifier selected_character_identifier; // 0x30
        [Key("compare_source_array")] public TrainingRoadmapCompareSource[] compare_source_array; // 0x38
        [Key("compare_friend_trained_chara_array")] public TrainedChara[] compare_friend_trained_chara_array; // 0x40
        [Key("single_mode_reserved_race_array")] public SingleModeReservedRaceDeck[] single_mode_reserved_race_array; // 0x48
        [Key("generate_succession_reserved_race_array")] public SingleModeReservedRaceDeck[] generate_succession_reserved_race_array; // 0x50
        [Key("generate_succession_support_card_deck_array")] public UserSupportCardDeck[] generate_succession_support_card_deck_array; // 0x58
        [Key("tutorial_info")] public TrainingRoadmapTutorialInfo tutorial_info; // 0x60
    }
}
