// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapUpdateSelectedCharacterRequest>))]
public class TrainingRoadmapUpdateSelectedCharacterRequest : RequestBase<TrainingRoadmapUpdateSelectedCharacterResponse>
{
    [Key("identifier")] public TrainingRoadmapCharacterIdentifier identifier; // 0x88
}
