// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapRemovePlanResponse>))]
public class TrainingRoadmapRemovePlanResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapRemovePlanResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapRemovePlanResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("character_array")] public TrainingRoadmapChara[] character_array; // 0x10
        [Key("succession_character_array")] public TrainingRoadmapSuccessionChara[] succession_character_array; // 0x18
        [Key("compare_source_array")] public TrainingRoadmapCompareSource[] compare_source_array; // 0x20
        [Key("compare_friend_trained_chara_array")] public TrainedChara[] compare_friend_trained_chara_array; // 0x28
    }
}
