// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapRemoveSuccessionPlanRequest>))]
public class TrainingRoadmapRemoveSuccessionPlanRequest : RequestBase<TrainingRoadmapRemoveSuccessionPlanResponse>
{
    [Key("plan_id")] public int plan_id; // 0x88
}
