// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapAddSuccessionCharacterResponse>))]
public class TrainingRoadmapAddSuccessionCharacterResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapAddSuccessionCharacterResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapAddSuccessionCharacterResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("succession_character_array")] public TrainingRoadmapSuccessionChara[] succession_character_array; // 0x10
    }
}
