// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapUpdateSuccessionCharacterRequest>))]
public class TrainingRoadmapUpdateSuccessionCharacterRequest : RequestBase<TrainingRoadmapUpdateSuccessionCharacterResponse>
{
    [Key("succession_character")] public TrainingRoadmapSuccessionChara succession_character; // 0x88
}
