// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapRemoveCharacterRequest>))]
public class TrainingRoadmapRemoveCharacterRequest : RequestBase<TrainingRoadmapRemoveCharacterResponse>
{
    [Key("plan_id")] public int plan_id; // 0x88
}
