// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapAddSuccessionCharacterRequest>))]
public class TrainingRoadmapAddSuccessionCharacterRequest : RequestBase<TrainingRoadmapAddSuccessionCharacterResponse>
{
    [Key("succession_character")] public TrainingRoadmapSuccessionChara succession_character; // 0x88
}
