// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapSetCompareRequest>))]
public class TrainingRoadmapSetCompareRequest : RequestBase<TrainingRoadmapSetCompareResponse>
{
    [Key("compare_source")] public TrainingRoadmapCompareSource compare_source; // 0x88
}
