// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapPreImportShareRequest>))]
public class TrainingRoadmapPreImportShareRequest : RequestBase<TrainingRoadmapPreImportShareResponse>
{
    [Key("share_id")] public long share_id; // 0x88
}
