// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapUpdateSelectedCharacterResponse>))]
public class TrainingRoadmapUpdateSelectedCharacterResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapUpdateSelectedCharacterResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapUpdateSelectedCharacterResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("selected_character_identifier")] public TrainingRoadmapCharacterIdentifier selected_character_identifier; // 0x10
        [Key("auto_call_skill_set_deck_id")] public int auto_call_skill_set_deck_id; // 0x18
    }
}
