// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapSetCompareResponse>))]
public class TrainingRoadmapSetCompareResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapSetCompareResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapSetCompareResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("compare_source_array")] public TrainingRoadmapCompareSource[] compare_source_array; // 0x10
        [Key("compare_friend_trained_chara_array")] public TrainedChara[] compare_friend_trained_chara_array; // 0x18
        [Key("is_auto_delete_by_sync")] public bool is_auto_delete_by_sync; // 0x20
    }
}
