// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainerSkillActivateRequest>))]
public class TrainerSkillActivateRequest : RequestBase<TrainerSkillActivateResponse>
{
    [Key("current_trainer_skill_pt")] public long current_trainer_skill_pt; // 0x88
    [Key("activate_trainer_skill_array")] public TrainerSkillActivateTrainerSkill[] activate_trainer_skill_array; // 0x90
    [Key("current_maintenance_id_array")] public int[] current_maintenance_id_array; // 0x98
}
