// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapPreSetCompareRequest>))]
public class TrainingRoadmapPreSetCompareRequest : RequestBase<TrainingRoadmapPreSetCompareResponse>
{
    [Key("compare_source")] public TrainingRoadmapCompareSource compare_source; // 0x88
}
