// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingReportSavePurchaseDialogReadTimeResponse>))]
public class TrainingReportSavePurchaseDialogReadTimeResponse : ResponseCommon
{
    [Key("data")] public TrainingReportSavePurchaseDialogReadTimeResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingReportSavePurchaseDialogReadTimeResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
