// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapAddCharacterRequest>))]
public class TrainingRoadmapAddCharacterRequest : RequestBase<TrainingRoadmapAddCharacterResponse>
{
    [Key("character")] public TrainingRoadmapChara character; // 0x88
}
