// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapChara>))]
public class TrainingRoadmapChara
{
    [Key("plan_id")] public int plan_id; // 0x10
    [Key("card_id")] public int card_id; // 0x14
    [Key("speed")] public TrainingRoadmapCharaStatus speed; // 0x18
    [Key("stamina")] public TrainingRoadmapCharaStatus stamina; // 0x20
    [Key("power")] public TrainingRoadmapCharaStatus power; // 0x28
    [Key("guts")] public TrainingRoadmapCharaStatus guts; // 0x30
    [Key("wiz")] public TrainingRoadmapCharaStatus wiz; // 0x38
    [Key("ground")] public int ground; // 0x40
    [Key("proper_ground")] public int proper_ground; // 0x44
    [Key("distance")] public int distance; // 0x48
    [Key("proper_distance")] public int proper_distance; // 0x4C
    [Key("running_style")] public int running_style; // 0x50
    [Key("proper_running_style")] public int proper_running_style; // 0x54
    [Key("top_skill_id_array")] public int[] top_skill_id_array; // 0x58
    [Key("high_skill_id_array")] public int[] high_skill_id_array; // 0x60
    [Key("low_skill_id_array")] public int[] low_skill_id_array; // 0x68
    [Key("support_card_id_array")] public int[] support_card_id_array; // 0x70
}
