// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapShareResponse>))]
public class TrainingRoadmapShareResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapShareResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapShareResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("share_id")] public long share_id; // 0x10
        [Key("expiration_time")] public string expiration_time; // 0x18
        [Key("same_content_share_info_array")] public TrainingRoadmapSameContentShareInfo[] same_content_share_info_array; // 0x20
        [Key("remaining_daily_share_count")] public int remaining_daily_share_count; // 0x28
    }
}
