// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapTutorialFinishResponse>))]
public class TrainingRoadmapTutorialFinishResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapTutorialFinishResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapTutorialFinishResponse.CommonResponse>))]
    public class CommonResponse
    {
    }
}
