// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapGetFriendTrainedCharaRequest>))]
public class TrainingRoadmapGetFriendTrainedCharaRequest : RequestBase<TrainingRoadmapGetFriendTrainedCharaResponse>
{
    [Key("is_get_friend_info")] public bool is_get_friend_info; // 0x88
}
