// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapPreSetCompareResponse>))]
public class TrainingRoadmapPreSetCompareResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapPreSetCompareResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapPreSetCompareResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("compare_source_array")] public TrainingRoadmapCompareSource[] compare_source_array; // 0x10
        [Key("added_friend_trained_chara_array")] public TrainedChara[] added_friend_trained_chara_array; // 0x18
    }
}
