// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapTutorialInfo>))]
public class TrainingRoadmapTutorialInfo
{
    [Key("tutorial_step")] public int tutorial_step; // 0x10
    [Key("tutorial_share_id")] public long tutorial_share_id; // 0x18
}
