// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapUpdateCharacterRequest>))]
public class TrainingRoadmapUpdateCharacterRequest : RequestBase<TrainingRoadmapUpdateCharacterResponse>
{
    [Key("character")] public TrainingRoadmapChara character; // 0x88
}
