// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapRemoveSuccessionPlanResponse>))]
public class TrainingRoadmapRemoveSuccessionPlanResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapRemoveSuccessionPlanResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapRemoveSuccessionPlanResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("succession_character_array")] public TrainingRoadmapSuccessionChara[] succession_character_array; // 0x10
        [Key("compare_source_array")] public TrainingRoadmapCompareSource[] compare_source_array; // 0x18
        [Key("compare_friend_trained_chara_array")] public TrainedChara[] compare_friend_trained_chara_array; // 0x20
    }
}
