// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainerSkillTrainerSkill>))]
public class TrainerSkillTrainerSkill
{
    [Key("trainer_skill_id")] public int trainer_skill_id; // 0x10
    [Key("active_end_time")] public long active_end_time; // 0x18
}
