// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainerSkillIndexResponse>))]
public class TrainerSkillIndexResponse : ResponseCommon
{
    [Key("data")] public TrainerSkillIndexResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainerSkillIndexResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("trainer_skill_info")] public TrainerSkillInfo trainer_skill_info; // 0x10
        [Key("last_activate_id_array")] public int[] last_activate_id_array; // 0x18
        [Key("new_trainer_skill_last_check_time")] public long new_trainer_skill_last_check_time; // 0x20
    }
}
