// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapSelectedInfo>))]
public class TrainingRoadmapSelectedInfo
{
    [Key("selected_character_identifier")] public TrainingRoadmapCharacterIdentifier selected_character_identifier; // 0x10
    [Key("character")] public TrainingRoadmapChara character; // 0x18
    [Key("succession_character")] public TrainingRoadmapSuccessionChara succession_character; // 0x20
    [Key("compare_source_array")] public TrainingRoadmapCompareSource[] compare_source_array; // 0x28
}
