// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapUpdateSuccessionPlanResponse>))]
public class TrainingRoadmapUpdateSuccessionPlanResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapUpdateSuccessionPlanResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapUpdateSuccessionPlanResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("succession_plan")] public TrainingRoadmapSuccessionPlan succession_plan; // 0x10
    }
}
