// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapCharaStatus>))]
public class TrainingRoadmapCharaStatus
{
    [Key("value")] public int value; // 0x10
    [Key("is_set")] public bool is_set; // 0x14
}
