// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapRemoveCharacterResponse>))]
public class TrainingRoadmapRemoveCharacterResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapRemoveCharacterResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapRemoveCharacterResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("character_array")] public TrainingRoadmapChara[] character_array; // 0x10
    }
}
