// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapGetSharedHistoryResponse>))]
public class TrainingRoadmapGetSharedHistoryResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapGetSharedHistoryResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapGetSharedHistoryResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("shared_chara_info_array")] public TrainingRoadmapSharedInfo[] shared_chara_info_array; // 0x10
        [Key("shared_succession_chara_info_array")] public TrainingRoadmapSharedInfo[] shared_succession_chara_info_array; // 0x18
    }
}
