// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapCopyRequest>))]
public class TrainingRoadmapCopyRequest : RequestBase<TrainingRoadmapCopyResponse>
{
    [Key("paste_identifier")] public TrainingRoadmapCharacterIdentifier paste_identifier; // 0x88
    [Key("copy_identifier")] public TrainingRoadmapCharacterIdentifier copy_identifier; // 0x90
    [Key("copy_type")] public int copy_type; // 0x98
}
