// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainerSkillInfo>))]
public class TrainerSkillInfo
{
    [Key("trainer_skill_array")] public TrainerSkillTrainerSkill[] trainer_skill_array; // 0x10
}
