// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapShareRequest>))]
public class TrainingRoadmapShareRequest : RequestBase<TrainingRoadmapShareResponse>
{
    [Key("identifier")] public TrainingRoadmapCharacterIdentifier identifier; // 0x88
}
