// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingReportSavePurchaseDialogReadTimeRequest>))]
public class TrainingReportSavePurchaseDialogReadTimeRequest : RequestBase<TrainingReportSavePurchaseDialogReadTimeResponse>
{
    [Key("season_id")] public int season_id; // 0x88
}
