// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapUpdateSuccessionPlanRequest>))]
public class TrainingRoadmapUpdateSuccessionPlanRequest : RequestBase<TrainingRoadmapUpdateSuccessionPlanResponse>
{
    [Key("succession_plan")] public TrainingRoadmapSuccessionPlan succession_plan; // 0x88
}
