// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainerSkillActivateTrainerSkill>))]
public class TrainerSkillActivateTrainerSkill
{
    [Key("trainer_skill_id")] public int trainer_skill_id; // 0x10
    [Key("activate_num")] public int activate_num; // 0x14
}
