// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapChangedPlanData>))]
public class TrainingRoadmapChangedPlanData
{
    [Key("changed_plan_array")] public TrainingRoadmapPlan[] changed_plan_array; // 0x10
    [Key("changed_succession_plan_array")] public TrainingRoadmapSuccessionPlan[] changed_succession_plan_array; // 0x18
    [Key("is_changed_friend_trained_chara")] public bool is_changed_friend_trained_chara; // 0x20
    [Key("friend_trained_chara_array")] public TrainedChara[] friend_trained_chara_array; // 0x28
}
