// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapRemoveSuccessionCharacterRequest>))]
public class TrainingRoadmapRemoveSuccessionCharacterRequest : RequestBase<TrainingRoadmapRemoveSuccessionCharacterResponse>
{
    [Key("identifier")] public TrainingRoadmapCharacterIdentifier identifier; // 0x88
}
