// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapCharacterIdentifier>))]
public class TrainingRoadmapCharacterIdentifier
{
    [Key("type")] public int type; // 0x10
    [Key("plan_id")] public int plan_id; // 0x14
    [Key("position_id")] public int position_id; // 0x18
}
