// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapOverwriteByTrainedCharaRequest>))]
public class TrainingRoadmapOverwriteByTrainedCharaRequest : RequestBase<TrainingRoadmapOverwriteByTrainedCharaResponse>
{
    [Key("identifier")] public TrainingRoadmapCharacterIdentifier identifier; // 0x88
    [Key("trained_chara_id")] public int trained_chara_id; // 0x90
    [Key("owner_viewer_id")] public long owner_viewer_id; // 0x98
    [Key("use_type")] public int use_type; // 0xA0
    [Key("overwrite_type")] public int overwrite_type; // 0xA4
}
