// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapRemoveSuccessionCharacterResponse>))]
public class TrainingRoadmapRemoveSuccessionCharacterResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapRemoveSuccessionCharacterResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapRemoveSuccessionCharacterResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("succession_character_array")] public TrainingRoadmapSuccessionChara[] succession_character_array; // 0x10
    }
}
