// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapGetShareInfoResponse>))]
public class TrainingRoadmapGetShareInfoResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapGetShareInfoResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapGetShareInfoResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("same_content_share_info_array")] public TrainingRoadmapSameContentShareInfo[] same_content_share_info_array; // 0x10
        [Key("remaining_daily_share_count")] public int remaining_daily_share_count; // 0x18
        [Key("has_shared_history")] public bool has_shared_history; // 0x1C
    }
}
