// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapSharedInfo>))]
public class TrainingRoadmapSharedInfo
{
    [Key("type")] public int type; // 0x10
    [Key("share_id")] public long share_id; // 0x18
    [Key("title")] public string title; // 0x20
    [Key("character")] public TrainingRoadmapChara character; // 0x28
    [Key("succession_character_array")] public TrainingRoadmapSuccessionChara[] succession_character_array; // 0x30
    [Key("expiration_time")] public string expiration_time; // 0x38
}
