// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapUpdateCharacterResponse>))]
public class TrainingRoadmapUpdateCharacterResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapUpdateCharacterResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapUpdateCharacterResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("character")] public TrainingRoadmapChara character; // 0x10
    }
}
