// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapImportShareResponse>))]
public class TrainingRoadmapImportShareResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapImportShareResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapImportShareResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("character_array")] public TrainingRoadmapChara[] character_array; // 0x10
        [Key("succession_character_array")] public TrainingRoadmapSuccessionChara[] succession_character_array; // 0x18
    }
}
