// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainerSkillSaveNotifyLastCheckTimeRequest>))]
public class TrainerSkillSaveNotifyLastCheckTimeRequest : RequestBase<TrainerSkillSaveNotifyLastCheckTimeResponse>
{
    [Key("save_time")] public long save_time; // 0x88
}
