// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapGetFriendTrainedCharaResponse>))]
public class TrainingRoadmapGetFriendTrainedCharaResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapGetFriendTrainedCharaResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapGetFriendTrainedCharaResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("friend_trained_chara_array")] public TrainedChara[] friend_trained_chara_array; // 0x10
        [Key("event_trained_chara_array")] public TrainedChara[] event_trained_chara_array; // 0x18
        [Key("friend_load_info")] public FriendLoadInfo friend_load_info; // 0x20
    }
}
