// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapImportShareForTutorialRequest>))]
public class TrainingRoadmapImportShareForTutorialRequest : RequestBase<TrainingRoadmapImportShareForTutorialResponse>
{
    [Key("share_id")] public long share_id; // 0x88
    [Key("target_identifier")] public TrainingRoadmapCharacterIdentifier target_identifier; // 0x90
}
