// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapExtendShareResponse>))]
public class TrainingRoadmapExtendShareResponse : ResponseCommon
{
    [Key("data")] public TrainingRoadmapExtendShareResponse.CommonResponse data; // 0x18

    [MessagePackObject]
    [MessagePackFormatter(typeof(GallopMessagePackFormatter<TrainingRoadmapExtendShareResponse.CommonResponse>))]
    public class CommonResponse
    {
        [Key("expiration_time")] public string expiration_time; // 0x10
        [Key("same_content_share_info_array")] public TrainingRoadmapSameContentShareInfo[] same_content_share_info_array; // 0x18
        [Key("remaining_daily_share_count")] public int remaining_daily_share_count; // 0x20
    }
}
