// <auto-generated> Gallop protocol compiler output. Do not edit by hand.

using MessagePack;

namespace Gallop;

[MessagePackObject]
[MessagePackFormatter(typeof(GallopMessagePackFormatter<UmaplanCumulativePurchaseBonusInfo>))]
public class UmaplanCumulativePurchaseBonusInfo
{
    [Key("bonus_received_dialog_disp_flag")] public bool bonus_received_dialog_disp_flag; // 0x10
    [Key("current_month_of_continuous_purchase")] public int current_month_of_continuous_purchase; // 0x14
}
